---
version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    maxBytes: 5242880
    backupCount: 5
    encoding: utf8

loggers:
  "":
    level: ERROR
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file_handler]